### ISSUE TITLE
Procedures Folder is recreated on every "php artisan updatesql". 

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/laravel-sql-views#7]
Both mysql Views and Procedures folders should be deletable by the developer. Ideally they should be created when the package is installed, and perhaps through a specific command that can be run manually, but right now they are recreated on each "php artisan updatesql" call, which is not ideal for automated deployments.

**Comment by vwmoose** [comment]
This is an annoyance for me too, I don't even have to run the `updateSql` command for it to re-appear each time.  Perhaps a config file change to prevent the `/database/procedures/example-proc.sql` being created every time the service provider is registered?

**Comment by vwmoose** [comment]
@dave-mills I've created a PR with the above changes but obviously can't push it up.  If you're interested let me know.  Thanks for developing the package in the first place!

**Comment by dave-mills** [comment]
@vwmoose glad you find this package useful! Yes please for the PR - I guess you made it on a local clone of this repo -  I've added you as a collaborator so hopefully you can now push your branch and add a PR for it?
